version: "3.9"
services:
  app:
    image: registry.gitlab.com/sustineo/simdesk:2.4.0
    ports:
      - "8085:8080"
    volumes:
      - ./data:/app/data
      - ./results:/app/results
    environment:
      SPRING_PROFILES_ACTIVE: acc-leaderboard, acc-entrylist, acc-raceapp, acc-bop, discord
      SIMDESK_IMPRESSUM_URL: https://markracing.de/impressum
      SIMDESK_PRIVACY_URL: https://markracing.de/privacy
      SIMDESK_COMMUNITY_NAME: Sim2Real
      SIMDESK_ACC_RESULTS_IGNORE_PATTERNS: "(No leaderboard)+"
      SIMDESK_DISCORD_CLIENT_ID: ${SIMDESK_DISCORD_CLIENT_ID}
      SIMDESK_DISCORD_CLIENT_SECRET: ${SIMDESK_DISCORD_CLIENT_SECRET}
      SIMDESK_DISCORD_BOT_TOKEN: ${SIMDESK_DISCORD_BOT_TOKEN}
      SIMDESK_DISCORD_GUILD_ID: ${SIMDESK_DISCORD_GUILD_ID}
    env_file:
      - .env
    restart: unless-stopped
