version: "3.9"
services:
  database:
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=acc_leaderboard
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    restart: unless-stopped