spring:
  application:
    name: acc-leaderboard
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      fail-on-unknown-properties: false
  flyway:
    create-schemas: true
    schemas: acc_leaderboard
    default-schema: acc_leaderboard
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "info,health,prometheus"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
leaderboard:
  links:
    impressum: ${LEADERBOARD_IMPRESSUM_URL:}
    privacy: ${LEADERBOARD_PRIVACY_URL:}
  results:
    folder: ${LEADERBOARD_RESULTS_FOLDER:/opt/acc-leaderboard/results}

---
spring:
  config:
    activate:
      on-profile: "mysql"
  datasource:
    url: "jdbc:mysql://localhost:3306/acc_leaderboard"
    username: "root"
    password: "my-secret-pw"

---
spring:
  config:
    activate:
      on-profile: "development"
logging:
  level:
    ROOT: INFO
    de.sustineo.acc.leaderboard: DEBUG
    de.sustineo.acc.leaderboard.entities.mapper: INFO

---
spring:
  config:
    activate:
      on-profile: "production"
  main:
    banner-mode: off
logging:
  level:
    ROOT: WARN
vaadin:
  productionMode: true
  heartbeatInterval: 60
  closeIdleSessions: true