spring:
  application:
    name: acc-leaderboard
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      fail-on-unknown-properties: false
  task:
    scheduling:
      pool:
        size: 4
  flyway:
    create-schemas: true
    schemas: main
    default-schema: main

management:
  endpoints:
    web:
      exposure:
        include: "info,health,metrics"
  info:
    java:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: "production"
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:file:./data/accLeaderboardsData"