spring:
  application:
    name: acc-server-tools
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      fail-on-unknown-properties: false
  flyway:
    create-schemas: true
    schemas: acc_leaderboard
    default-schema: acc_leaderboard
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "info,health,prometheus"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
leaderboard:
  links:
    impressum: ${LEADERBOARD_IMPRESSUM_URL:}
    privacy: ${LEADERBOARD_PRIVACY_URL:}
  results:
    folder: ${LEADERBOARD_RESULTS_FOLDER:/opt/acc-server-tools/results}
    scan_interval: ${LEADERBOARD_RESULTS_SCAN_INTERVAL:PT1M}

---
spring:
  config:
    activate:
      on-profile: "mysql"
  datasource:
    url: ${LEADERBOARD_DATASOURCE_URL}
    username: ${LEADERBOARD_DATASOURCE_USERNAME:root}
    password: ${LEADERBOARD_DATASOURCE_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: "development"
logging:
  level:
    ROOT: INFO
    de.sustineo.acc.servertools: DEBUG
    de.sustineo.acc.servertools.entities.mapper: INFO

---
spring:
  config:
    activate:
      on-profile: "production"
  main:
    banner-mode: off
logging:
  level:
    ROOT: INFO
vaadin:
  productionMode: true
  heartbeatInterval: 60
  closeIdleSessions: true