spring:
  application:
    name: acc-leaderboard
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      fail-on-unknown-properties: false
  flyway:
    create-schemas: true
    schemas: acc_leaderboard
    default-schema: acc_leaderboard

management:
  endpoints:
    web:
      exposure:
        include: "info,health,metrics"
  info:
    java:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: "production"
  datasource:
    url: "jdbc:mysql://localhost:3306/acc_leaderboard"
    username: "root"
    password: "my-secret-pw"