name: simdesk-deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment'
        required: true
      version:
        type: string
        description: 'Version'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: [ self-hosted, sustineo-01 ]
    environment:
      name: ${{ inputs.environment }}
      url: "https://${{ inputs.environment }}.simdesk.eu"
    defaults:
      run:
        working-directory: ${{ vars.TARGET_DIR }}
    env:
      SIMDESK_VERSION: ${{ inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ vars.CONTAINER_REGISTRY }} -u ${{ github.actor }} --password-stdin
      - name: Copy docker compose file
        run: cp -f ${{ github.workspace }}/docker-compose.yml docker-compose.yml
      - name: docker compose up
        run: docker compose up -d